### PR TITLE
feat(floating-modal): rewrite floating modal using interactjs

### PR DESCRIPTION
**Pull request by boiarchukk**
Rewrite Floating Modal component
## Description

Previous version of Floating Modal has some limitations. Using [Interactjs](https://interactjs.io/), component will be without its previous version flaws, like:

1. Not inertial throwing
2. Not responsive dragging events
3. Doesn't support multiple simultaneous interactions

## Screenshots:
**Before** (If applicable):

**After**:

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by futurethang** [comment]
Works great in the sandbox. Question: does the Floating modal intentionally not have a 'click-outside-to-close' feature? I can't tell if it is missing or purposefully not there.

**Comment by boiarchukk** [comment]
> Works great in the sandbox. Question: does the Floating modal intentionally not have a 'click-outside-to-close' feature? I can't tell if it is missing or purposefully not there.

As I remember, this feature is not included in basic requirements. @helen-v can you please clear this moment ?

**Comment by helen-v** [comment]
Floating modal shouldn't have outside click, because modal should stay opened and agent can work on screen with different blocks.

**Review by helen-v — DISMISSED** [review]
As I Understand modal should minimise, so that we can shrink the window to its minimum size.

**Comment by boiarchukk** [comment]
> As I Understand modal should minimise, so that we can shrink the window to its minimum size.

Done

**Review by yananym — APPROVED** [review]

**Pull request merged**
