### PR TITLE
feat(react:Tab): Add option to not automatically scroll Tab(s) into view

### PR DESCRIPTION
**Pull request by eazy-g**
## Description
Add option for consumer to specify that a Tab should not be scrolled into view upon focus. The current implementation is particularly annoying for tabs that are not in view initally on a page - e.g. the middle of the page (or wherever the tabs are located) is scrolled into view upon landing on the page.

Also, remove "javascript:void(0)" as React adds a warning to browser console: "A future version of React will block javascript: URLs as a security precaution. Use event handlers instead if you can."

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by jbirori** [comment]
Doesn't look like this is working on Safari for me, but seems to work on Chrome and Firefox. Good catch with regards to the `javascript:void(0)` stuff, but instead of removing the href altogether, could you use [one of these methods](https://github.com/facebook/react/issues/16382#issuecomment-607252694) suggested by React team? Concerned that removing the `href` altogether would mess with the accessibility tabbing

**Comment by eazy-g** [comment]
image

Weird, appears safari probably doesn't support the option. Maybe I'll prevent the call to `.focus()` altogether if the new prop present

And yes, will add the href back in!

**Comment by jbirori** [comment]
LGTM! @jcatalan-cisco I think this is good to merge in unless if we want another set of eyes on it 👍🏽

**Review by jbirori — APPROVED** [review]

**Comment by jcatalan-cisco** [comment]
@eazy-g please just merge the latest base branch changes here and then I'll merge 👍

**Comment by eazy-g** [comment]
Thanks @jcatalan-cisco just hung up on a percy diff now

**Comment by jcatalan-cisco** [comment]
@eazy-g I did the override on the percy test, but there is another that seems stuck. Maybe you can force push and retrigger?

**Comment by eazy-g** [comment]
Hmm, this `test_web_components` step still sticking @jcatalan-cisco

**Pull request merged**
