### PR TITLE
feat(core/input): add color theming

### PR DESCRIPTION
**Pull request by InteractiveTimmy**
# Description

The scope of the changes in this pull request are to add css theming variables to the `input` core component.

[SPARK-218761](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-218761)

# Motivation and Context

The changes in this PR are to meet presented requirements for the new theming.

# How Has This Been Tested?

Live user testing was done to confirm that the changes properly impacted the components without impacting existing use cases.

# Screenshots

Screen Shot 2021-04-22 at 11 34 55 AM
Screen Shot 2021-04-22 at 11 34 45 AM

# Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

# Checklist
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Coread** [comment]
From the look of the percy tests the spinning part of the spinner has disappeared in a number of cases

**Comment by futurethang** [comment]
In addition to the concern raised by @Coread , is there any updates to Documentation that might be needed?

**Comment by InteractiveTimmy** [comment]
> In addition to the concern raised by @Coread , is there any updates to Documentation that might be needed?

Currently, this feature isn't available for general usage. Documentation would further expose these changes to consumers.

**Comment by futurethang** [comment]
@InteractiveTimmy check this remaining Percy diff too, it looks like a spacing style changed

**Comment by InteractiveTimmy** [comment]
> @InteractiveTimmy check this remaining Percy diff too, it looks like a spacing style changed

My changes don't affect spacing, and is scoped only to colors. This may have been introduced by a different PR. Reviewing recent changes now to this project now.

**Pull request merged**
