### PR TITLE
feat(tooltip) Center aligning tooltip text for Angular

### PR DESCRIPTION
**Pull request by kjeree**
## Description
Angular's `md-tooltip` did not follow the specification in https://momentum.design/components/tooltip/style, which says that text alignment should be centered.

## Related Issue
https://github.com/momentum-design/momentum-ui/issues/494

## Motivation and Context
The fix makes the library follow the documented examples. I assume the examples are correct, because other libraries than Angular seem to be consistent with documentation.

## How Has This Been Tested?
After making the (trivial) change, I loaded it up in the Momentum project's Playground, and verified that it now looks good.

## Screenshots:
tooltip_before

**After**:

after_change

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by kjeree** [comment]
> Did someone change the design? 

Not to my knowledge, I think the working assumption should be that the Angular component was implemented incorrectly from the get-go. 

> Why do we want all tooltips center aligned at all times? 

Cisco Webex Control Hub has it like that for all code that's using the AngularJS `md-toolkit`, i.e. the overwhelming majority of the product. Now that we've started migrating Control Hub from AngularJS to Angular, we see that Momentum's Angular components behave differently. Because Control Hub has used Momentum for quite some time without anyone complaining, we assume that the AngularJS behavior is correct, and the Angular behavior is incorrect.

>Maybe this should be added as a alternate property?

Perhaps, but I would still recommend defaulting to center aligning.

**Comment by mathsusan** [comment]
Can you kick off a build again to see if the checks will pass?

**Comment by daanishnasir** [comment]
@kjeree can you take out the 🐛 in the committ message and re-format

feat(component-name) : center aligning tooltip text

**Comment by kjeree** [comment]
> @kjeree can you take out the 🐛 in the committ message and re-format

Sure. I by the way used `yarn commit` to create the original commit; if this tool produces commit messages on a format we don't want, perhaps we should update (or remove) it?

**Comment by pauljeter** [comment]
@kjeree that's a valid point. I'll look at it.

**Pull request merged**
