### PR TITLE
fix(icon-build): ensure that rebuilds of icons produce the same output

### PR DESCRIPTION
**Pull request by paulwitty**
## Description
I got fed up that rebuilding the icon files produced a massive diff every time, even if the inputs hadn't changed. This was because a timestamp (of now) was used in the file. I've changed this to instead use the timestamp of the last git commit in the icons/svg directory, which seems like a much better timestamp to use.

## Screenshots:
**Before** (If applicable):

**After**:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by paulwitty** [comment]
@futurethang afraid I haven't fixed that, because I wasn't aware of the problem. I'll see if I can think of a way to make it consistent...

**Comment by futurethang** [comment]
@paulwitty cool cool. for reference, see what `icons.scss` is all about at `momentum-ui/icons/scss/icons.scss`

**Review by lismith2-cisco — COMMENTED** [review]
I suggest building icons & committing as part of this PR so everything is in a good state

**Comment by paulwitty** [comment]
@futurethang 
Each icon gets mapped to a glyph in the font file, starting from a fixed point and then assigning glyphs sequentially in alphabetical order of icon names. So if you add an icon with a name beginning with a, all the icons get new glyphs, resulting in much bigger diffs.

We could fix that by:
a) choosing glyphs using a hash of the name, so it's consistent, but we'll get collisions so it's only mostly consistent
b) using the previous mapping as an input to the new mapping, but if you remove and then re-add an icon it'll still get a different glyph

But we have an scss file which provides the mapping of name to glyph, and we always use that to refer to icons anyway, so the only benefit we get is reducing the size of diffs (on generated files), and I don't consider that worth putting in the effort

**Review by lismith2-cisco — APPROVED** [review]

**Comment by futurethang** [comment]
@paulwitty @lismith2-cisco OK cool let's merge this, but please keep a sharp eye out for any Icon trouble in the chat spaces.

**Pull request merged**
