### PR TITLE
Aindi/cx-8565 : Provide collapse/expand capability for grouped options in combobox.

### PR DESCRIPTION
**Pull request by vikcool2pr**
#CX-8575 : Provide expand/collapse capability for grouped options in combobox.
## Description
1) Allow grouped options to be expand/collapsable.
2) Default grouped options will be collapsed.
3) Search matched options will be listed from all the groups
4) Key board navigation handled with
    !) key down to go through the group and enter/space to expand.
    !!) tab will help to nevigate through group headers ignoring options.
    !!!) key down/up will allow to navigate grouped options & Enter/space on options will select the option.

## Screenshots:
**Before** (If applicable):

**After**:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by parsoman — APPROVED** [review]

**Comment by vikcool2pr** [comment]
BUILD

**Comment by vikcool2pr** [comment]
BUILD

**Review by parsoman — APPROVED** [review]

**Comment by vikcool2pr** [comment]
BUILD

**Review by parsoman — APPROVED** [review]

**Review by aigoel — APPROVED** [review]

**Comment by vikcool2pr** [comment]
BUILD

**Pull request merged**
