### PR TITLE
feat(www): add component status page

### PR DESCRIPTION
**Pull request by wzpo**
Add www components status page

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kbsmth** [comment]
@wzpo can you adjust these tabs to fit the current type of tabs being used on the site?

Screen Shot 2019-12-11 at 2 50 34 PM

**Comment by wzpo** [comment]
@kbsmth I will update accordingly.

**Comment by wzpo** [comment]
@pauljeter fixed

**Comment by pauljeter** [comment]
@wzpo, you need to resolve the conflicts before this PR can be merged.

**Comment by wzpo** [comment]
@pauljeter It seems everything is updated and I cannot rebase to solve the conflicts.

**Pull request merged**
