### PR TITLE
refactor(core/event-overlay): remove box-shadow

### PR DESCRIPTION
**Pull request by InteractiveTimmy**
## Description

The scope of the changes in this pull request are to remove the drop-shadow effects on pop-overs, as they are negatively impacting theming, and are typically unnoticed otherwise.

## Related Issue

HOTFIX

## Motivation and Context

Drop-shadows on this component aren't flexible enough to apply with variable background colors. This causes unwanted halo effects around components when the contrast between its color and the lower z-index component's color is high.

## Screenshots:
**Before** (If applicable):

Screen Shot 2021-05-13 at 11 29 54 AM

**After**:

Screen Shot 2021-05-13 at 11 29 31 AM

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by yjlo — APPROVED** [review]
LGTM

**Review by Coread — CHANGES_REQUESTED** [review]
This has broken loads of thing where they rely on the background e.g. tooltips, popovers

**Comment by yjlo** [comment]
From Percy I can see that, popovers have no outline anymore which is a problem

**Comment by torgeadelin** [comment]
LGTM

**Review by torgeadelin — APPROVED** [review]

**Review by yjlo — APPROVED** [review]

**Review by Coread — APPROVED** [review]

**Pull request merged**
