### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by jeffhoang**
Remove node's upper bound restriction

## Description
We're trying to upgrade our application to nodeJS 17 and we need this upper bound restriction removed.

## Related Issue
N/A

## Motivation and Context
Upgrading application to nodeJS 17

## How Has This Been Tested?
We have our own unit tests with 100% coverage.

## Screenshots:
N/A

**After**:
N/A

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:
- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jeffhoang** [comment]
@ArthusLiang , will you review this?

**Review by ArthusLiang — APPROVED** [review]

**Comment by jeffhoang** [comment]
Will you also merge this? I'm not authorized to do so.

**Comment by jeffhoang** [comment]
How do I run the above CI tests? I don't have access to circleci.

**Comment by ArthusLiang** [comment]
To some reason. This PR can not start the CI. Submitted another one.

**Pull request closed without merging**
