### PR TITLE
build(tokens): redirect paths, initial setup of token NPM module

### PR DESCRIPTION
**Pull request by futurethang**
This is a draft of a re-working to the tokens library, starting with Color tokens. The objective is to move these references to an independent library to be consumed as a module via NPM, and includes bot migrating the reference to a module and then changing reliant paths to use as such.

This is a rough draft for soliciting guidance on the best practices for such a migration.

## Description
Move colors.json into a top level library: `tokens/colors/colors.json`
Publish Tokens as NPM module
Refer to module dependency where styles and compilers refer to it from the Core library

## Motivation and Context
This move is intended to make the Monorepo more flexibly consumable.

## Screenshots:
**Before** (If applicable):

**After**:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bfbiggs** [comment]
I think the paths need to be fixed so the tests can run correctly.  Also does the Tokens directory need versioning (I can see the reasoning behind it).  If so should those updates be included in the CI config?

**Comment by futurethang** [comment]
@bfbiggs Which paths are you referring to, those that need to refer to color.js? @pauljeter mentioned in an aside this also needs Lerna configured. Does that interface with the CI, or is the CO another config? Apologies for the ambiguous approach, I'm learning on the move with this library.

**Comment by futurethang** [comment]
Added updates that need feedback, I'm unsure why those tests are failing.

**Comment by bfbiggs** [comment]
Can we squash these commits?

**Comment by elenagiere** [comment]
> Can we squash these commits?



> Can we squash these commits?



> Can we squash these commits?

Hi Ben, I think it's a great idea to squash the commits. I have been trying to debug the ci:test for days and I was trying to get them all the pass. Would you know anything about why the test_react and percy/ommentum-ui tests aren't passing?

**Comment by pauljeter** [comment]
I pulled the PR and ran it locally. Looks like the examples are showing in the app and that's why the tests are failing. Need to look into this and see why they are not showing in the app.
image

**Pull request merged**
